### ISSUE TITLE
Where to get the hardware

### ISSUE THREAD

**Issue by MTrab** [jnxxx/homeassistant-dabblerdk_powermeterreader#1]
This looks really promising for Echelon users, but - 

Where to buy the MEB hardware?
You are referring to dabbler.dk site, but I can't seem to find any way to buy the hardware

**Comment by jnxxx** [comment]
The protocol is still under NDA, thus the firmware cannot currently be published, unfortunately.
NES is working on a specification that can be published, and then Dabbler.dk also plans to publish what they have.
I am not sure they are planning to produce and sell it. Or it will just be published and you can build your own.

**Comment by MTrab** [comment]
Can you then publish the hardware files, so we can buy/make the hardware so we are ready for when the firmware will be available?

**Comment by jnxxx** [comment]
I don't have it. I only made the HA integration.
For everything related to the HW, please see Dabbler.dk. You can also make a comment there.

**Comment by AMajland** [comment]
@MTrab I'm not able to make the nice integrated board hw myself :-( surface mount components are to small for me.

But Christian Lerche (https://lerchetech.dk/) has offered his support on dabbler.dk and plans to look at in (2022 August time frame) 

I started a discussion with Energi Midt (Now N1) back in 2013 to get access to my own data. Even trough the law is clear :

> “§ 7. Det skal være muligt for forbrugeren efter åbne standarder at tilkoble eksterne enheder til den fjernaflæste elmåler og løbende udtage forbrugsrelevante data,”

The first answer was just : "no way you can get access" (because they had started fitting these meters before § 7 was added to the law.

The discussion has then progressed over the years with which type of meters since it was established that i have the right to a meter with a different different measurement principe (because i have photovoltaic systems - summation over phases instead of threating them independent) 

But event if i paid to get my meter changed i would be out of luck. They just answered that it also had a MEP port in the new meters and that was open enough to fulfill the law. I got that answer as late as Mai 2019 .... They didn't care that no interface was available for that standard or that it was not open ....  But thanks to the guys at dabbler.dk i know have the MEP basic key

I'm sure there is market for a populated module - just not sure how big :-) 

https://github.com/orgs/OSGP-Alliance-MEP-and-Optical/discussions

Even though the MEP module in the drawer is a real nice and elegant solution i can get by with less (won't be able to solder surface mount components anyway). My meter is in a closed cabinet so a prototype connected with wires would do just fine - the Ruko lock should keep it safe enough :-)

When Dabbler release the code for their board i'll have a look at using it on populated board esp32 board and a RS232-TTL converter. But their issues with fake MAX3232 makes me suspect that many of the readymade TTL converters will have the same issues ... But have a ESP32 running with a TTL to RS485 converter to my solar inverter

**Comment by glynge** [comment]
Hi @MTrab and @AMajland 
I'm one of the dabblers from www.dabbler.dk.
Our main goal was to get the protocols released and the secondary gold is to release our hard- and software. It will be fully free and available for everyone, but unfortunately we currently have limited time (as usual). We are planning to setup a GitHub with both Hard- and Software so other can contribute to this...
We have reached out to get others involved and hope that they will start providing/selling kits and assembled boards.
We currently have both a THT (true hole technology) and a SMD version of the PCB - but we actually have not yet had the time to populate and test the latest version.
If you (or anyone else) write me an e-mail on gert@dabbler.dk, I'll share the KiCad and software files with you... Now the NDA has been lifted there is no secrets (although we wish we had time to finish stuff a bit more :-) )...
Best regards,
Gert Lynge

**Comment by jnxxx** [comment]
See these links:

- [https://github.com/DabblerDK](https://github.com/DabblerDK)
- [https://www.dabbler.dk/index.php/2022/09/04/limited-offer-echelon-nes-smart-meters-mep-interfaces-modules-and-kits/](https://www.dabbler.dk/index.php/2022/09/04/limited-offer-echelon-nes-smart-meters-mep-interfaces-modules-and-kits/)

**Comment by AMajland** [comment]
My meter has just been replaced  to one without the MEP interface. 

So I'll not need my MEP interface any more (SMD 2.0). 
Asking the samme 500DKK incl postage to Denmark as i paid for it.

(Gert / Dabbler.dk answered that they do not longer have a waiting list, otherwise i would have sold to the top of the list)

![image](https://user-images.githubusercontent.com/97510471/214788535-803a06b3-8fb6-4436-a2dd-f85d48120bac.png)
